# Site
repository: cjshearer/cjshearer.github.io
favicon: images/favicon.ico

# Personal info
name: Cody Shearer
title: Software Developer, Krumware | BS Computer Science, UofSC
email: cjshearer@live.com
# phone: Your phone number (optional)
# website: Your website (eg. https://google.com)(optional)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  cjshearer
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: cjshearer
# orcid_username: 0000-0000-0000-0000
# pinterest_username: jekyll
# stackoverflow_username: "00000001"
# youtube_username: globalmtb
# googleplus_username: +jekyll

# Additional icon links
# additional_links:
# - title: My Resum√©
#   icon: fas fa-file-pdf
#   url: ./resume/resume.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg

# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience


# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in ML and casual inference, some of my hobbies include
  parkour, gaming (including board games and DnD!) and carpentry.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
